CineCrud/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CineCrud.Models
{
    public class ApplicationDbContext: DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }

        public DbSet<Cine> Cine { get; set; }
    }
}

CineCrud/Models/Cine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CineCrud.Models
{
    public class Cine
    {
        [Key]
        public int idMov { get; set; }

        [Required(ErrorMessage = "Ingrese titulo de la pelicula")]
        [Display(Name = "Titulo")]
        public string tituloM { get; set; }

        [Required(ErrorMessage = "Ingrese genero de la pelicula")]
        [Display(Name = "Genero")]
        public string generoM { get; set; }

        [Required(ErrorMessage = "Ingrese fecha de reservacion")]
        [Display(Name = "Reservacion")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        [DataType(DataType.Date)]
        public DateTime fechaM { get; set;}

       
        [Required(ErrorMessage = "Ingrese horario")]
        [Display(Name = "Horario (24hrs)")]
        public string horario { get; set; }


        [Required(ErrorMessage = "Ingrese nombre de quien reserva")]
        [Display(Name = "Reservo: ")]
        public string reservoM { get; set; }

        [Required(ErrorMessage ="Ingrese numero de boletos")]
        [Display(Name ="Asientos:")]
        public int asientos { get; set; }

        [Required(ErrorMessage ="Forma de pago")]
        [Display(Name ="Pago")]
        public string tipoPago { get; set; }
    }
}

CineCrud/Models/ErrorViewModel.cs
using System;

namespace CineCrud.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CineCrud/Controllers/CineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CineCrud.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CineCrud.Controllers
{
    public class CineController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CineController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var displaydata = _db.Cine.ToList();
            return View(displaydata);
        }


        [HttpGet]
        public async Task<IActionResult> Index(string movSearch)
        {
            ViewData["GetCineDetails"] = movSearch;
            var empquery = from x in _db.Cine select x;
            if (!String.IsNullOrEmpty(movSearch))
            {
                empquery = empquery.Where(x => x.tituloM.Contains(movSearch) ||
                x.reservoM.Contains(movSearch));
            }
            return View(await empquery.AsNoTracking().ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Cine nMov)
        {
            if (ModelState.IsValid)
            {
                _db.Add(nMov);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nMov);
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getCineDetail = await _db.Cine.FindAsync(id);
            return View(getCineDetail);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getCineDetail = await _db.Cine.FindAsync(id);
            return View(getCineDetail);
        }


        [HttpPost]
        public async Task<ActionResult> Edit(Cine oldRes)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldRes);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldRes);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getCineDetail = await _db.Cine.FindAsync(id);
            return View(getCineDetail);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {

            var getCineDetail = await _db.Cine.FindAsync(id);
            _db.Cine.Remove(getCineDetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

CineCrud/Views/Cine/Create.cshtml
@model CineCrud.Models.Cine

@{
    ViewData["Title"] = "Create";
}

<h1>Nueva reservacion</h1>

<h4>Cine</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="tituloM" class="control-label"></label>
                <input asp-for="tituloM" class="form-control" />
                <span asp-validation-for="tituloM" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="generoM" class="control-label" style="width:600px;"></label>
                <select name="generoM" style="width:350px;">
                    <option value="">Selecciona</option>
                    <option value="Accion">Accion</option>
                    <option value="Aventura">Aventura</option>
                    <option value="Comedia">Comedia</option>
                    <option value="Infantil">Infantil</option>
                    <option value="Terror">Terror</option>
                    <option value="Romance">Romance</option>
                </select>
            </div>

            <div class="form-group">
                <label asp-for="fechaM" class="control-label"></label>
                <input asp-for="fechaM" class="form-control" />
                <span asp-validation-for="fechaM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="horario" class="control-label"></label>
                <input asp-for="horario" class="form-control" />
                <span asp-validation-for="horario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="reservoM" class="control-label"></label>
                <input asp-for="reservoM" class="form-control" />
                <span asp-validation-for="reservoM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="asientos" class="control-label"></label>
                <input asp-for="asientos" class="form-control" />
                <span asp-validation-for="asientos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tipoPago" class="control-label" style="width:600px;"></label>
                <select name="tipoPago" style="width:350px;">
                    <option value="">Selecciona</option>
                    <option value="Efectivo">Efectivo</option>
                    <option value="Tarjeta_debito">Tarjeta de debito</option>
                    <option value="Tarjeta_credito">Tarjeta de credito</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CineCrud/Views/Cine/Delete.cshtml
@model CineCrud.Models.Cine

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Seguro de querer eliminar reservación?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idMov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tituloM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tituloM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.generoM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.generoM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.fechaM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.fechaM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.horario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.horario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.reservoM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.reservoM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.asientos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.asientos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tipoPago)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tipoPago)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar</a>
    </form>
</div>

CineCrud/Views/Cine/Detail.cshtml
@model CineCrud.Models.Cine

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalles</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idMov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tituloM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tituloM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.generoM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.generoM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.fechaM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.fechaM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.horario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.horario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.reservoM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.reservoM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.asientos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.asientos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tipoPago)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tipoPago)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Regresar</a>
</div>

CineCrud/Views/Cine/Edit.cshtml
@model CineCrud.Models.Cine

@{
    ViewData["Title"] = "Edit";
}

<h1>Modificar</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idMov" class="control-label"></label>
                <input asp-for="idMov" class="form-control" readonly />
                <span asp-validation-for="idMov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tituloM" class="control-label"></label>
                <input asp-for="tituloM" class="form-control" />
                <span asp-validation-for="tituloM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="generoM" class="control-label" style="width:600px;"></label>
                <select name="generoM" style="width:350px;">
                    <option value="">Selecciona</option>
                    <option value="Accion">Accion</option>
                    <option value="Aventura">Aventura</option>
                    <option value="Comedia">Comedia</option>
                    <option value="Infantil">Infantil</option>
                    <option value="Terror">Terror</option>
                    <option value="Romance">Romance</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="fechaM" class="control-label"></label>
                <input asp-for="fechaM" class="form-control" />
                <span asp-validation-for="fechaM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="horario" class="control-label"></label>
                <input asp-for="horario" class="form-control" />
                <span asp-validation-for="horario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="reservoM" class="control-label"></label>
                <input asp-for="reservoM" class="form-control" />
                <span asp-validation-for="reservoM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="asientos" class="control-label"></label>
                <input asp-for="asientos" class="form-control" />
                <span asp-validation-for="asientos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tipoPago" class="control-label" style="width:600px;"></label>
                <select name="tipoPago" style="width:350px;">
                    <option value="">Selecciona</option>
                    <option value="Efectivo">Efectivo</option>
                    <option value="Tarjeta_debito">Tarjeta de debito</option>
                    <option value="Tarjeta_credito">Tarjeta de credito</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CineCrud/Views/Cine/Index.cshtml
@model IEnumerable<CineCrud.Models.Cine>

@{
    ViewData["Title"] = "Index";
}

<h1>Cine Star</h1>

<p>
    <a asp-action="Create">Nueva reservación</a>
</p>

<form asp-action="Index" method="get">
        <input type="search" placeholder="Busca por titulo o por persona" name="movSearch"
               value="@ViewData["GetCineDetails"]" style="width:300px;" />
        <input type="submit" value="Buscar" class="btn btn-outline-dark" />
        <a asp-action="Index" class="btn btn-outline-dark">Ver todos</a>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.idMov)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tituloM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.generoM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fechaM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.horario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.reservoM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.asientos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tipoPago)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.idMov)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tituloM)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.generoM)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fechaM)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.horario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.reservoM)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.asientos)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tipoPago)
                </td>
                <td>
                    @Html.ActionLink("Detalles", "Detail", new { id = item.idMov }, new { @class = "btn btn-outline-warning" })
                    @Html.ActionLink("Modificar", "Edit", new { id = item.idMov }, new { @class = "btn btn-outline-success" })
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.idMov }, new { @class = "btn btn-outline-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>

CineCrud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CineCrud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body background="img/cine.jpg">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Cine" asp-action="Index">CineCrud</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cine" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CineCrud
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>